<a href="https://colab.research.google.com/github/ankush-003/Learning-ML-Basics/blob/main/Python_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.random.randn(5)

In [ ]:
a

array([ 0.48571843,  0.11472766,  0.33659291,  0.95187777, -0.48070917])

In [ ]:
# rank 1 array
a.shape

(5,)

In [ ]:
a.T

array([ 0.48571843,  0.11472766,  0.33659291,  0.95187777, -0.48070917])

In [ ]:
np.dot(a,a.T)

7.743386586823526

In [ ]:
a = np.random.randn(5,1)
print(a)

[[ 0.3181546 ]
 [-0.29215591]
 [ 0.99307883]
 [-0.04554812]
 [ 0.07829376]]


In [ ]:
a.shape

(5, 1)

In [ ]:
a.T

array([[ 0.3181546 , -0.29215591,  0.99307883, -0.04554812,  0.07829376]])

In [ ]:
#outer product
print(np.dot(a,a.T))

[[ 0.10122235 -0.09295075  0.3159526  -0.01449134  0.02490952]
 [-0.09295075  0.08535508 -0.29013385  0.01330715 -0.02287398]
 [ 0.3159526  -0.29013385  0.98620556 -0.04523287  0.07775187]
 [-0.01449134  0.01330715 -0.04523287  0.00207463 -0.00356613]
 [ 0.02490952 -0.02287398  0.07775187 -0.00356613  0.00612991]]
