Numpy Arrays


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
mat = np.array([[1,2,3],[4,5,6]])

In [4]:
mat.shape

(2, 3)

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# returns evenly spaced 10 elements
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(3,3)

array([[0.55472497, 0.95397911, 0.81093148],
       [0.30044529, 0.04280161, 0.95225436],
       [0.30071614, 0.49655514, 0.30283051]])

In [12]:
np.random.rand(5)

array([0.55796392, 0.29349641, 0.39781006, 0.04763339, 0.81072241])

In [13]:
np.random.randn(2,2)

array([[ 0.46110629,  1.5321675 ],
       [ 1.64821268, -2.10712069]])

In [14]:
normal_points = np.random.randn(10)
# plt.plot(normal_points)

In [15]:
np.random.randint(1,100,(3,3))

array([[93, 81, 99],
       [57, 80, 46],
       [95, 52,  6]])

In [16]:
arr = np.arange(25)

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.max(), arr.min()

(24, 0)

In [21]:
ranarr.argmax()

6

In [22]:
arr.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5).shape

(5, 5)

In [24]:
arr.dtype

dtype('int64')