## NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[:7:2]

array([0, 2, 4, 6])

In [6]:
arr[0:5:2] = 69
arr

array([69,  1, 69,  3, 69,  5,  6,  7,  8,  9, 10])

In [7]:
#Broadcasting
slice_array = arr
slice_array[:3] = 68
arr

array([68, 68, 68,  3, 69,  5,  6,  7,  8,  9, 10])

In [8]:
arr_copy = arr.copy()
arr_copy

array([68, 68, 68,  3, 69,  5,  6,  7,  8,  9, 10])

In [9]:
arr_copy[0] = 69
arr

array([68, 68, 68,  3, 69,  5,  6,  7,  8,  9, 10])

In [10]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [11]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
arr_2d[0][0]

5

In [13]:
arr_2d[0,0]

5

In [18]:
arr_2d[0:2, 0:2]

array([[ 5, 10],
       [20, 25]])

In [19]:
arr2 = np.arange(1,11)

In [20]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
bool_arr = arr2 > 5

In [27]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
arr2[bool_arr]

array([ 6,  7,  8,  9, 10])

In [30]:
arr2[arr2> 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr3 = np.arange(50).reshape(5,10)

In [32]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
arr3[arr3 % 5 == 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [34]:
arr3[1:4, 3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])