In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
b = np.array([1,2,3,4,546,3,65,785,42,54,54,2,3,5,4,345,53,23,])
b.shape

(18,)

In [4]:
# b = b.reshape(6,3) # 6 rows and 3 columns
# b
# b.reshape(6,3)
b

array([  1,   2,   3,   4, 546,   3,  65, 785,  42,  54,  54,   2,   3,
         5,   4, 345,  53,  23])

In [5]:
# np.argsort returns the indices that would sort an array
print(np.argsort(b))
print("index of smallest element and value: {},{}".format(np.argmin(b),b[np.argmin(b)]))
print("index of largest element and value: {},{}".format(np.argmax(b),b[np.argmax(b)]))

[ 0  1 11  2  5 12  3 14 13 17  8 16 10  9  6 15  4  7]
index of smallest element and value: 0,1
index of largest element and value: 7,785


In [15]:
b = b.reshape(6,3)
print(b)
print(np.argsort(b,axis=0),np.argsort(b,axis=1),sep='\n\n')

[[  1   2   3]
 [  4 546   3]
 [ 65 785  42]
 [ 54  54   2]
 [  3   5   4]
 [345  53  23]]
[[0 0 3]
 [4 4 0]
 [1 5 1]
 [3 3 4]
 [2 1 5]
 [5 2 2]]

[[0 1 2]
 [2 0 1]
 [2 0 1]
 [2 0 1]
 [0 2 1]
 [2 1 0]]
