In [2]:
import numpy as np
array1 = np.array([[1,2,3.0,4,5,6],[1,124,4343,45,69,70]],dtype='int32')
print(type(array1)) # n dimensional array
print(array1)

<class 'numpy.ndarray'>
[[   1    2    3    4    5    6]
 [   1  124 4343   45   69   70]]


In [4]:
print(array1.shape)
print(array1.dtype)
print(array1)

(2, 6)
int32
[[   1    2    3    4    5    6]
 [   1  124 4343   45   69   70]]


In [3]:
# np.zeros(4)
np.zeros((4,6)) #creates 4x6 array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
arr2 = np.ones((4,6))
print(arr2,"type is: " + str(arr2.dtype),sep='\n')

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
type is: float64


In [5]:
np.empty((2,2)) # all elements need not be zeroes can be garbage values also

array([[4.64152150e-310, 0.00000000e+000],
       [4.64212473e-310, 4.64212479e-310]])

In [6]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [7]:
print(array * array) # not matrix multiplication but element wise
print(array - array)
print(array + array)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [8]:
1/array

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [9]:
np.array([12.0**20])

array([3.83375999e+21])

## Slicing

In [10]:
array2 = np.array([1,2,3,4,5,6])


In [11]:
arr = array2[2:4]

In [12]:
print(array2,arr)

[1 2 3 4 5 6] [3 4]


In [13]:
arr[1] = 69
print(array2,arr)

[ 1  2  3 69  5  6] [ 3 69]


In [14]:
arrCpy = array2[2:4].copy()

In [15]:
arrCpy[1] = 70
print(array2,arrCpy)

[ 1  2  3 69  5  6] [ 3 70]
