# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
# dtypes: np.int8, np.int32, np.int64
myarray = np.array([1,2,3,4,5],np.int32)
myarray

array([1, 2, 3, 4, 5])

In [3]:
myarr1 = np.array([[1,2,3]])
myarr1[0,2]

3

In [4]:
print("myarr1 shape {} data type {}".format(myarr1.shape,myarr1.dtype))

myarr1 shape (1, 3) data type int32


## Array Creation from **Python Objects**

In [5]:
listArr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
# for efficiency we only use int and float arrays
dictArr = np.array([{'a':1,'b':2},{'a':3,'b':4}])
dictArr

array([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}], dtype=object)

In [7]:
zeros = np.zeros((3,4))
print(zeros, zeros.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float64


In [8]:
rng = np.arange(10)
print(rng, rng.dtype)

[0 1 2 3 4 5 6 7 8 9] int32


In [9]:
# np.linespace is similar to np.arange but it takes the number of elements
lspace = np.linspace(0,10,5)
print(lspace, lspace.dtype)

[ 0.   2.5  5.   7.5 10. ] float64


In [10]:
# np.empty creates an array with random values
emp = np.empty((3,4))
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# empty_like creates an array with random values of the same shape as the input array
emp_like = np.empty_like(lspace)
print(emp_like, emp_like.dtype)

[ 0.   2.5  5.   7.5 10. ] float64


In [12]:
# np.identity creates an identity matrix
iden = np.identity(5)
print(iden, iden.dtype,iden.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] float64 (5, 5)


## Reshaping Arrays

In [13]:
arr = np.arange(50)
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] (50,)


In [14]:
# number of elements must be equal to the number of elements in the array
arr = arr.reshape(5,10)
print(arr, arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] (5, 10)


In [15]:
# np.ravel flattens the array
arr = arr.ravel()
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] (50,)


In [16]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# axis = 0 is the rows
# axis = 1 is the columns
print("row sum: ",ar.sum(axis=1))
print("column sum: ",ar.sum(axis=0))

row sum:  [ 6 15 24]
column sum:  [12 15 18]


In [18]:
print("transpose: ",ar.T)

transpose:  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
print("flatten: ",ar.flatten())
for i in ar.flatten():
    print(i,end=" ")

flatten:  [1 2 3 4 5 6 7 8 9]
1 2 3 4 5 6 7 8 9 

In [20]:
print("number of dimensions: ",ar.ndim)

number of dimensions:  2


In [21]:
print("number of elements: ",ar.size)

number of elements:  9


In [22]:
print("total bytes: ",ar.nbytes)

total bytes:  36


In [23]:
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
ar1 = np.array([1,2,3,33,9,12])
print("index of max: ",ar1.argmax())
print("max element",ar1[ar1.argmax()])
print("index of min: ",ar1.argmin())
print("min element",ar1[ar1.argmin()])

index of max:  3
max element 33
index of min:  0
min element 1


In [25]:
# gives the index elements of the array that satisfy the condition
ar1.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [26]:
# for 2d arrays
print(ar)
print("index of max: ",ar.argmax())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
index of max:  8


In [27]:
print("index of max along axis 0: (column max)",ar.argmax(axis=0))

index of max along axis 0: (column max) [2 2 2]


In [28]:
print("index of max along axis 1: (row max)",ar.argmax(axis=1))

index of max along axis 1: (row max) [2 2 2]


In [29]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [30]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ar.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [33]:
art = ar.T
art

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar + art

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [35]:
# extend the list
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [36]:
ar * art

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [37]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [38]:
print("sum of all elements: ",ar.sum())
print("max of all elements: ",ar.max())

sum of all elements:  45
max of all elements:  9


In [39]:
#finding elements in an array
# np.where returns the index of the elements that satisfy the condition
print(ar)
print(np.where(ar>=5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [40]:
np.count_nonzero(ar)

9

In [41]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [42]:
import sys

In [43]:
np_ar = np.arange(1000)

In [44]:
py_ar = list(range(1000))

In [45]:
# numpy array is more efficient
print("numpy array size: ",sys.getsizeof(np_ar))
print("python array size: ",sys.getsizeof(py_ar))

numpy array size:  4112
python array size:  8056


In [46]:
sys.getsizeof(py_ar[0]) * len(py_ar)

24000

In [47]:
np_ar.itemsize * np_ar.size

4000

In [48]:
# tolist converts the numpy array to a python list
print(ar.tolist(),type(ar.tolist()))
print(type(ar))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
<class 'numpy.ndarray'>


Reference: 
- [codewithharry.com](https://www.youtube.com/watch?v=Rbh1rieb3zc)
- [numy docs](https://numpy.org/doc/stable/reference/arrays.ndarray.html)
